resources:
  - pvc-mysql.yaml
  - deployment-mysql.yaml
  - service-mysql.yaml
namespace: wordpress

secretGenerator:
- name: mysql-pass
  envs:
  - .env.secret
  
generatorOptions:
 disableNameSuffixHash: true