apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: wordpress.miniminipenguenler.com
    http:
      paths:
      - path: /wordpress(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: wordpress-service
            port:
              number: 80